### ISSUE TITLE
allow negative numbers in textarea when setting alerts

### ISSUE THREAD

**Issue by kchandar** [carowa/hios-project#32]

**Comment by Inouju** [comment]
Negative numbers aren't really possible. 

A percent change is always positive, and currency value must be greater than 0.

**Comment by kchandar** [comment]
@Inouju Can't percent changes be negative? doesn't "it was a 4% drop" mean a -4% change?

**Comment by Inouju** [comment]
@kchandar I thought that would mean a 4% change regardless of drop or gain, since it's just a "change".
